version: '3.1'

services:

  db:
    image: postgres:12
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: post
      POSTGRES_USER: post
    volumes:
      - /Users/bortikovsv/VM_Postgres/backup
      - /Users/bortikovsv/VM_Postgres/main
