#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII4cIdZwM4PctTlmWO+5GkFGQzJgOArwYFwTb/ItOqKs bortikovsv@MacBook-Air-BortikovSV.local
package_update: true
package_upgrade: false
packages:
 - vim
 - nginx
