---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"
  name: clickhouse 

- src: git@github.com:Rain-m-a-n/lighthouse-role.git
  scm: git
  version: "v1.0.0"
  name: ligthouse-role

- src: git@github.com:Rain-m-a-n/vector-role.git
  scm: git
  version: "v1.0.0"
  name: vector-role

    