apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kuber-1-3
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.2
          ports:
          - protocol: TCP
            containerPort: 80

        - name: multitool
          image: dergeberl/multitool:v0.7
          ports:
            - protocol: TCP
              containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: multitool
  namespace: kuber-1-3
  labels:
    cont: multitool
spec:
  containers:
    - name: multitool
      image: dergeberl/multitool:v0.7
      ports:
        - protocol: TCP
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: task1-svc
  namespace: kuber-1-3
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80


