version: '3.8'

services:
  mysql:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: post
      POSTGRES_USER: postgres
    volumes:
      - /Users/bortikovsv/VM_Postgres/backup:/db_backup
      - /Users/bortikovsv/VM_Postgres/main:/db_data

