---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
        dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
      with_items: "{{ clickhouse_packages }}"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
- name: Install Vector
  hosts: vector
  handlers:
    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Get Distrib Vector
      become: true
      ansible.builtin.yum:
        name: "https://packages.timber.io/vector/{{ vector_ver }}/vector-1.x86_64.rpm"
        state: present
      notify: Start Vector service
- name: Install Lighthouse
  hosts: lighthouse
  handlers:
    - name: Restart nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  pre_tasks:
    - name: Lighthouse | install dependencies
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  tasks:
    - name: EPEL-release | Install
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: NGNIX | Install
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Lighthouse | copy from git
      become: true
      git:
        repo: "{{ lighthouse_repo }}"
        version: master
        dest: "{{ lighthouse_path }}"
    - name: lighthouse | Create lighthouse config
      become: true
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Restart nginx service
    - name: Flush handllush_handleers
      meta: flush_handlers
    - name: FIREWALL | Add Rules
      changed_when: false
      become: true
      shell: |
        firewall-cmd --permanent --add-service=http
        firewall-cmd --reload
