---
apiVersion: v1
kind: Namespace
metadata:
  name: kuber-3-4

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kuber-3-4
  labels:
    app: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: kuber-3-4
spec:
  selector:
    app: backend
  ports:
    - name: multitool
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kuber-3-4
  labels:
    app: frontend
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.28

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: kuber-3-4
spec:
  selector:
    app: frontend
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP